package colorclash.view;

import colorclash.utils.AudioManager;
import colorclash.utils.Config;
import colorclash.model.GameModel;
import colorclash.model.IGameModel;

import javax.swing.JFrame;
import javax.swing.JPanel;

import java.awt.CardLayout;//DOC: A CardLayout object is a layout manager for a container.
                           // It treats each component in the container as a card.
                           // Only one card is visible at a time, and the container acts as a stack of cards.
import java.awt.Container;
import java.awt.event.WindowAdapter; // DOC: An abstract adapter class for receiving window events. 
                                     // The methods in this class are empty. This class exists as convenience for creating listener objects.
import java.awt.event.WindowEvent;//DOC:A low-level event that indicates that a window has changed its status.
                                  //This low-level event is generated by a Window object when it is opened, closed, activated,


public class MainFrame extends JFrame {
    
    // variabili d'istanza
    private CardLayout cardLayout;
    private JPanel mainPanel;
    private GamePanel gamePanel;
    private MenuPanel menuPanel;
    private PausePanel pausePanel;
    private IGameModel model; // <-- USO L'INTERFACCIA

    // costanti
    private final int FRAME_WIDTH = Config.getInstance().getIntProperty("frame_width");
    private final int FRAME_HEIGHT = Config.getInstance().getIntProperty("frame_height");

    public MainFrame() {
        // UNICO PUNTO IN CUI SI CHIAMA IL SINGLETON
        model = GameModel.getInstance(); 
        initialSettings();
        frameStructureBuilder();
    }// fine costruttore

    //METODI PUBBLICI
    
    public void changeFrame(String panelName) {

        cardLayout.show(mainPanel, panelName);

        if (panelName.equals("GAME")) {
            mainPanel.getComponent(1).requestFocusInWindow();
        }
        if (panelName.equals("PAUSE")) {
            AudioManager.getInstance().stopBackgroundMusic();
            AudioManager.getInstance().playBackgroundMusic("pause.wav");
            
        }
        if (panelName.equals("MENU")) {
            AudioManager.getInstance().stopBackgroundMusic();
            AudioManager.getInstance().playBackgroundMusic("menu.wav");
        }
    }// fine changeFrame

    //METODI PRIVATI

    private void initialSettings() {
        setTitle("Color Clash");
        setSize(FRAME_WIDTH, FRAME_HEIGHT);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);//DOC: Sets the location of the window relative to the specified component according to the following scenarios.
                                      //If the component is null, or the GraphicsConfiguration associated with this component is null,
                                      // the window is placed in the center of the screen. 
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                if (gamePanel.isVisible()) {
                    if (model != null) {
                        model.autoSave();
                    }
                }
                AudioManager.getInstance().closeAll();
                
                dispose();
                System.exit(0);
            }
        });
    }// fine initialSettings

    private void frameStructureBuilder() {
        Container contPane = getContentPane();
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);
        
        // INIEZIONE DEL MODEL NEI PANNELLI
        menuPanel = new MenuPanel(this, model);
        gamePanel = new GamePanel(this, model);
        pausePanel = new PausePanel(this, model);
        
        mainPanel.add(menuPanel, "MENU");
        mainPanel.add(gamePanel, "GAME");
        mainPanel.add(pausePanel, "PAUSE");
        contPane.add(mainPanel);
        cardLayout.show(mainPanel, "MENU"); //DOC: Flips to the component that was added to this layout with the specified name, using addLayoutComponent.
    }// fine frameStructureBuilder

    // getters di MainFrame
    
    public GamePanel getGamePanel() {
        return gamePanel;
    }

    public MenuPanel getMenuPanel() {
        return menuPanel;
    }
}