package src.colorclash.view;

import src.colorclash.utils.AudioManager;
import src.colorclash.utils.Config;
import src.colorclash.model.GameModel;

import javax.swing.JFrame;
import javax.swing.JPanel;

import java.awt.CardLayout;//DOC: A CardLayout object is a layout manager for a container.
                           // It treats each component in the container as a card.
                           // Only one card is visible at a time, and the container acts as a stack of cards.
import java.awt.Container;
import java.awt.event.WindowAdapter; // DOC: An abstract adapter class for receiving window events. 
                                    // The methods in this class are empty. This class exists as convenience for creating listener objects.
import java.awt.event.WindowEvent;
//DOC:A low-level event that indicates that a window has changed its status.
// This low-level event is generated by a Window object when it is opened, closed, activated,
// deactivated, iconified, or deiconified, or when focus is transferred into or out of the Window
//The event is passed to every WindowListener or WindowAdapter object which registered to receive such events using the window's addWindowListener method.
//(WindowAdapter objects implement the WindowListener interface.) Each such listener object gets this WindowEvent when the event occurs.

public class MainFrame extends JFrame {
    // variabili d'istanza
    private CardLayout cardLayout;
    private JPanel mainPanel;
    private GamePanel gamePanel;
    private MenuPanel menuPanel;
    private PausePanel pausePanel;
    private GameModel model;

    // costanti
    private final int FRAME_WIDTH = Config.getInstance().getIntProperty("frame_width");
    private final int FRAME_HEIGHT = Config.getInstance().getIntProperty("frame_height");

    public MainFrame() {
        model = GameModel.getInstance();
        initialSettings();
        frameStructureBuilder();
    }// fine costruttore

    //METODI PUBBLICI
    
    public void changeFrame(String panelName) {

        cardLayout.show(mainPanel, panelName);

        if (panelName.equals("GAME")) {
            mainPanel.getComponent(1).requestFocusInWindow();
        }
        if (panelName.equals("PAUSE")) {
            AudioManager.getInstance().stopBackgroundMusic();
            AudioManager.getInstance().playBackgroundMusic("pause.wav");
            
        }
        if (panelName.equals("MENU")) {
            AudioManager.getInstance().stopBackgroundMusic();
            AudioManager.getInstance().playBackgroundMusic("menu.wav");
        }
    }// fine changeFrame

    //METODI PRIVATI

    private void initialSettings() {
        setTitle("Color Clash");
        setSize(FRAME_WIDTH, FRAME_HEIGHT);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);//DOC: Sets the location of the window relative to the specified component according to the following scenarios.
                                    //If the component is null, or the GraphicsConfiguration associated with this component is null, the window is placed in the center of the screen. 
                                    // The center point can be obtained with the GraphicsEnvironment.getCenterPoint method.
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                if (gamePanel.isVisible()) {
                    if (model != null) {
                        model.autoSave();
                    }
                }
                AudioManager.getInstance().closeAll();
                
                dispose();  //Releases all of the native screen resources used by this Window, its subcomponents, and all of its owned children. 
                            //That is, the resources for these Components will be destroyed, any memory they consume will be returned to the OS, and they will be marked as undisplayable.
                System.exit(0); // Initiates the shutdown sequence of the Java Virtual Machine.
            }
        });
    }// fine initialSettings

    private void frameStructureBuilder() {
        Container contPane = getContentPane();
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);// non si può mettere direttamente in input 
        menuPanel = new MenuPanel(this);
        gamePanel = new GamePanel(this);
        pausePanel = new PausePanel(this);
        mainPanel.add(menuPanel, "MENU");
        mainPanel.add(gamePanel, "GAME");
        mainPanel.add(pausePanel, "PAUSE");
        contPane.add(mainPanel);
        cardLayout.show(mainPanel, "MENU"); //DOC: Flips to the component that was added to this layout with the specified name, using addLayoutComponent.
    }// fine frameStructureBuilder

    // GETTERS
    
    public GamePanel getGamePanel() {
        return gamePanel;
    }// fine getGamePanel

    public MenuPanel getMenuPanel() {
        return menuPanel;
    }// fine getMenuPanel
}